export const plantList = [
  "Aleppo Pine",
  "Atlas Cedar",
  "Holm Oak",
  "Cork Oak",
  "Algerian Oak",
  "Juniper",
  "Phoenician Juniper",
  "Wild Olive",
  "Carob Tree",
  "Pistachio Tree",
  "Atlas Pistachio",
  "Date Palm",
  "Acacia",
  "Tamarisk",
  "Desert Willow",
  "Eucalyptus",
  "Moringa",
  "Neem Tree",
  "Plane Tree",
  "Jacaranda",
  "Tipu Tree",
  "Silk Tree",
  "Chinaberry Tree",
  "Ash Tree",
  "Poplar",
  "Willow",
  "Elm",
  "Olive Tree",
  "Fig Tree",
  "Pomegranate",
  "Orange Tree",
  "Lemon Tree",
  "Mandarin Tree",
  "Apricot Tree",
  "Peach Tree",
  "Plum Tree",
  "Almond Tree",
  "Apple Tree",
  "Pear Tree",
  "Quince Tree",
  "Grape Vine",
  "Banana",
  "Wheat",
  "Barley",
  "Corn",
  "Sorghum",
  "Oats",
  "Chickpeas",
  "Lentils",
  "Fava Beans",
  "Peas",
  "Lupin",
  "Cotton",
  "Sunflower",
  "Sesame",
  "Sugar Beet",
  "Rosemary",
  "Thyme",
  "Lavender",
  "Sage",
  "Mint",
  "Basil",
  "Oregano",
  "Chamomile",
  "Artemisia",
  "Fenugreek",
  "Anise",
  "Cumin",
  "Coriander",
  "Bougainvillea",
  "Hibiscus",
  "Oleander",
  "Geranium",
  "Rose",
  "Jasmine",
  "Marigold",
  "Petunia",
  "Gazania",
  "Iris",
  "Gladiolus",
  "Chrysanthemum",
  "Prickly Pear",
  "Aloe Vera",
  "Agave",
  "Yucca",
  "Euphorbia",
  "Barrel Cactus",
  "Sansevieria",
  "Tomato",
  "Potato",
  "Onion",
  "Garlic",
  "Carrot",
  "Pepper",
  "Chili",
  "Zucchini",
  "Eggplant",
  "Lettuce",
  "Spinach",
  "Cucumber",
  "Cabbage",
  "Beach Grass",
  "Sea Fig",
  "Saltbush",
]
