import { EduPost } from "@/lib/edu/types"

export const eduCategories = [
  "Agronomy",
  "Solar energy",
  "Water management",
  "Climate & ecology",
  "Research & innovation",
]

export const eduPosts: EduPost[] = [
  {
    id: "edu-1",
    title: "Soil health check in 60 seconds",
    body: "A quick field test for soil texture, moisture, and organic matter.",
    category: "Agronomy",
    creator: {
      id: "creator-1",
      display_name: "Dr. Yasmine K.",
      expertise: "Soil science",
      verified: true,
      total_posts: 52,
      total_likes: 12400,
    },
    media_type: "video",
    media_urls: ["/edu/soil-health.mp4"],
    status: "verified",
    created_at: new Date().toISOString(),
    likes: 482,
    saves: 211,
    comments: 18,
  },
  {
    id: "edu-2",
    title: "Solar irrigation layout",
    body: "Best layout for drip lines powered by solar pumps in arid zones.",
    category: "Solar energy",
    creator: {
      id: "creator-2",
      display_name: "GreenLab Solar",
      expertise: "Renewable energy",
      verified: true,
      total_posts: 34,
      total_likes: 9800,
    },
    media_type: "infographic",
    media_urls: ["/edu/solar-irrigation.png"],
    status: "verified",
    created_at: new Date().toISOString(),
    likes: 318,
    saves: 144,
    comments: 9,
  },
  {
    id: "edu-3",
    title: "Water capture micro-basins",
    body: "Small basins improve infiltration and reduce runoff in semi-arid fields.",
    category: "Water management",
    creator: {
      id: "creator-3",
      display_name: "Amina H.",
      expertise: "Hydrology",
      verified: false,
      total_posts: 19,
      total_likes: 4200,
    },
    media_type: "carousel",
    media_urls: ["/edu/basin-1.jpg", "/edu/basin-2.jpg", "/edu/basin-3.jpg"],
    status: "needs_review",
    created_at: new Date().toISOString(),
    likes: 210,
    saves: 92,
    comments: 12,
  },
  {
    id: "edu-4",
    title: "Native biodiversity in coastal dunes",
    body: "Protect dune ecosystems by planting native stabilizers.",
    category: "Climate & ecology",
    creator: {
      id: "creator-4",
      display_name: "Eco Atlas",
      expertise: "Ecology",
      verified: true,
      total_posts: 40,
      total_likes: 11000,
    },
    media_type: "image",
    media_urls: ["/edu/dunes.jpg"],
    status: "verified",
    created_at: new Date().toISOString(),
    likes: 390,
    saves: 168,
    comments: 21,
  },
  {
    id: "edu-5",
    title: "Research brief: drought-resistant cultivars",
    body: "Summary of 2025 trials for drought-tolerant wheat varieties.",
    category: "Research & innovation",
    creator: {
      id: "creator-5",
      display_name: "Agro Research Lab",
      expertise: "Plant genetics",
      verified: true,
      total_posts: 64,
      total_likes: 14800,
    },
    media_type: "text",
    media_urls: [],
    status: "verified",
    created_at: new Date().toISOString(),
    likes: 512,
    saves: 290,
    comments: 33,
  },
]
