-- ============================================================
-- Education engagement tracking (posts + reels)
-- ============================================================

create table if not exists public.user_interactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  post_id uuid references public.edu_posts(id) on delete cascade,
  reel_id uuid references public.edu_reels(id) on delete cascade,
  interaction_type text not null,
  watch_time_seconds numeric(10,2) not null default 0 check (watch_time_seconds >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'user_interactions_target_check'
      and conrelid = 'public.user_interactions'::regclass
  ) then
    alter table public.user_interactions
      add constraint user_interactions_target_check
      check (((post_id is not null)::int + (reel_id is not null)::int) = 1);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'user_interactions_type_check'
      and conrelid = 'public.user_interactions'::regclass
  ) then
    alter table public.user_interactions
      add constraint user_interactions_type_check
      check (interaction_type in ('view', 'like', 'comment', 'share'));
  end if;
end;
$$;

create index if not exists idx_user_interactions_user_created
  on public.user_interactions (user_id, created_at desc);

create index if not exists idx_user_interactions_post_type_created
  on public.user_interactions (post_id, interaction_type, created_at desc)
  where post_id is not null;

create index if not exists idx_user_interactions_reel_type_created
  on public.user_interactions (reel_id, interaction_type, created_at desc)
  where reel_id is not null;

create index if not exists idx_user_interactions_post_views_watch
  on public.user_interactions (post_id, watch_time_seconds)
  where post_id is not null and interaction_type = 'view';

create index if not exists idx_user_interactions_reel_views_watch
  on public.user_interactions (reel_id, watch_time_seconds)
  where reel_id is not null and interaction_type = 'view';

alter table public.user_interactions enable row level security;

drop policy if exists "user_interactions: read own" on public.user_interactions;
create policy "user_interactions: read own"
  on public.user_interactions
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "user_interactions: insert own" on public.user_interactions;
create policy "user_interactions: insert own"
  on public.user_interactions
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "user_interactions: update own" on public.user_interactions;
create policy "user_interactions: update own"
  on public.user_interactions
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create or replace function public.user_interactions_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_user_interactions_set_updated_at on public.user_interactions;
create trigger trg_user_interactions_set_updated_at
before update on public.user_interactions
for each row execute function public.user_interactions_set_updated_at();

-- Client helper RPC for view/share/watch-time events.
create or replace function public.edu_track_interaction(
  p_interaction_type text,
  p_post_id uuid default null,
  p_reel_id uuid default null,
  p_watch_time_seconds numeric default 0,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  insert into public.user_interactions (
    user_id,
    post_id,
    reel_id,
    interaction_type,
    watch_time_seconds,
    metadata
  )
  values (
    auth.uid(),
    p_post_id,
    p_reel_id,
    lower(p_interaction_type),
    greatest(coalesce(p_watch_time_seconds, 0), 0),
    coalesce(p_metadata, '{}'::jsonb)
  );
end;
$$;

grant execute on function public.edu_track_interaction(text, uuid, uuid, numeric, jsonb) to authenticated;

-- Auto-harvest social interactions from existing likes/comments tables.
create or replace function public.edu_log_post_like_interaction()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_interactions (user_id, post_id, interaction_type, watch_time_seconds)
  values (new.user_id, new.post_id, 'like', 0);
  return new;
end;
$$;

drop trigger if exists trg_edu_log_post_like_interaction on public.edu_likes;
create trigger trg_edu_log_post_like_interaction
after insert on public.edu_likes
for each row execute function public.edu_log_post_like_interaction();

create or replace function public.edu_log_post_comment_interaction()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_interactions (user_id, post_id, interaction_type, watch_time_seconds)
  values (new.user_id, new.post_id, 'comment', 0);
  return new;
end;
$$;

drop trigger if exists trg_edu_log_post_comment_interaction on public.edu_comments;
create trigger trg_edu_log_post_comment_interaction
after insert on public.edu_comments
for each row execute function public.edu_log_post_comment_interaction();

create or replace function public.edu_log_reel_like_interaction()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_interactions (user_id, reel_id, interaction_type, watch_time_seconds)
  values (new.user_id, new.reel_id, 'like', 0);
  return new;
end;
$$;

drop trigger if exists trg_edu_log_reel_like_interaction on public.edu_reel_likes;
create trigger trg_edu_log_reel_like_interaction
after insert on public.edu_reel_likes
for each row execute function public.edu_log_reel_like_interaction();

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'user_interactions'
    ) then
      execute 'alter publication supabase_realtime add table public.user_interactions';
    end if;
  end if;
end;
$$;

select pg_notify('pgrst', 'reload schema');
